version: "3.7"
services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: quikdev-blog-dev-db
    environment:
      MYSQL_DATABASE: quikdev-blog
      MYSQL_PASSWORD: quikdev-blog
      MYSQL_ROOT_PASSWORD: quikdev-blog
      MYSQL_USER: quikdev-blog
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:5.7
    networks:
      - quikdev-blogNetwork
    ports:
      - 33306:3306
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - quikdev-blogMysqlData:/var/lib/mysql

networks:
  quikdev-blogNetwork:
    driver: bridge
volumes:
  quikdev-blogMysqlData:
    driver: local
    name: quikdev-blogMysqlData
